
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  selector:
    matchLabels:
      app: weatherapi-pod
  template:
    metadata:
      labels:
        app: weatherapi-pod
    spec:
      containers:
      - name: weatherapi-container
        image: acrweather.azurecr.io/weatherapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
